Merge images with woodby/drupal-php

diff --git a/5.3/Dockerfile b/5.3/Dockerfile
--- a/5.3/Dockerfile
+++ b/5.3/Dockerfile
@@ -1,4 +1,4 @@
-ARG FROM_TAG
+ ARG FROM_TAG
 
 FROM wodby/base-php:${FROM_TAG}
 
@@ -28,6 +28,17 @@ ENV PHP_DEV="${PHP_DEV}" \
     \
     GIT_USER_EMAIL="wodby@example.com" \
     GIT_USER_NAME="wodby"
+
+ENV DRUSH_VER="7.4.0" \
+    \
+    PHP_ALWAYS_POPULATE_RAW_POST_DATA="-1" \
+    PHP_MBSTRING_ENCODING_TRANSLATION="Off" \
+    PHP_MBSTRING_HTTP_INPUT="pass" \
+    PHP_MBSTRING_HTTP_OUTPUT="pass" \
+    PHP_OUTPUT_BUFFERING="16384" \
+    PHP_REALPATH_CACHE_SIZE="64k" \
+    PHP_REALPATH_CACHE_TTL="3600" \
+    PHP_SESSION_AUTO_START="0"
 
 RUN set -xe; \
     \
@@ -118,6 +129,8 @@ RUN set -xe; \
     mv /tmp/pkgs-bins/* /usr/bin; \
     \
     docker-php-source extract; \
+    \
+    docker-php-ext-configure imap --with-imap --with-imap-ssl; \
     \
     docker-php-ext-install \
         bcmath \
@@ -265,6 +278,24 @@ RUN set -xe; \
         rm -rf /usr/src/php.tar.xz; \
     fi
 
+RUN set -ex; \
+    \
+    # Drush
+    su-exec wodby composer global require drush/drush:"${DRUSH_VER}"; \
+    \
+    # Drush extensions
+    su-exec wodby mkdir -p /home/wodby/.drush; \
+    drush_patchfile_url="https://bitbucket.org/davereid/drush-patchfile.git"; \
+    su-exec wodby git clone "${drush_patchfile_url}" /home/wodby/.drush/drush-patchfile; \
+    \
+    mv /usr/local/bin/actions.mk /usr/local/bin/php.mk; \
+    # Change overridden target name to avoid warnings.
+    sed -i 's/git-checkout:/php-git-checkout:/' /usr/local/bin/php.mk; \
+    \
+    # Clean up
+    su-exec wodby composer clear-cache; \
+    su-exec wodby drush cc drush
+
 USER wodby
 
 WORKDIR ${APP_ROOT}
@@ -273,6 +304,7 @@ EXPOSE 9000
 COPY templates /etc/gotpl/
 COPY docker-entrypoint.sh /
 COPY bin /usr/local/bin/
+COPY init /docker-entrypoint-init.d/
 
 ENTRYPOINT ["/docker-entrypoint.sh"]
 CMD ["sudo", "-E", "php-fpm"]
